New spec for project 4
eecs370/eecs370.github.io pull request #43
Opened 2021-11-05 16:47 UTC by nelsontm

Synchronized with pull request in P4 Upgrade from branch "new-submission"
This spec details new output requirements and instructions for new starter code

2021-11-05 19:32 UTC, seshrs commented
Note that the preview URL for the spec is here: https://preview.sesh.rs/previews/eecs370/eecs370.github.io/43/projects/p4_spec.html

I think the main website page needs to change to include relative URLs to the specs. I can help put up a PR for that next week.

2021-11-07 16:07 UTC, jackphong commented
I noticed that there were quite a few comments in the starter code telling students how to use their project 1 simulator, or the project 1 instructor object file. I would recommend also adding some of these statements to the project spec under section 0, since staff members will most likely not be super familiar with the new project setup.

2021-11-10 01:29 UTC, Faryab commented on projects/p4_spec.md
> +}
Nit: This is bad style. Suggested change:
```
int mem_access(int addr, int write_flag, int write_data) {
    ++num_mem_accesses;
    if (write_flag) {
        state.mem[addr] = write_data;
    }
    return state.mem[addr];
}
```

2021-11-10 01:40 UTC, Faryab requested changes

2021-11-10 01:40 UTC, Faryab commented on projects/p4_spec.md
> +    printf("$$$ transferring word [%d-%d] ", address, address + size - 1);
Is there a specific reason we make this change?

2021-11-10 01:40 UTC, Faryab commented on projects/p4_spec.md
> +- Your cache simulator, a C program named `cache.c`
Can we keep this the same? (simulator.c) 

Not a huge ask but for MOSS you need to specify the file name, so for future cheatchecking these will have to be renamed to simulator or the past files will have to be renamed to cache.c

2021-11-10 01:40 UTC, Faryab commented on projects/p4_spec.md
> +in a separate file, ending in ".as", ".s", or ".lc2k"). Each test case
Why add more than just .as?

2021-11-10 01:40 UTC, Faryab commented on projects/p4_spec.md
> +Linux workstation using `gcc cache.c inst_p1s_sim.o -lm`, so your program should
Same comment about keeping `simulator.c` as above unless really necessary.

2021-11-10 13:50 UTC, nelsontm commented on projects/p4_spec.md
> +in a separate file, ending in ".as", ".s", or ".lc2k"). Each test case
I believe that enforcing files to be in .as is what is causing our weird unreadable characters. My theory is that when macs open files as actionscript, they automatically add some hidden characters that are messing up our autograder.

2021-11-10 13:51 UTC, danlliu commented on projects/p4_spec.md
> +in a separate file, ending in ".as", ".s", or ".lc2k"). Each test case
Can confirm this, I know people who opened their files in ActionScript and ended up with hidden characters everywhere.

2021-11-10 13:52 UTC, nelsontm commented on projects/p4_spec.md
> +    printf("$$$ transferring word [%d-%d] ", address, address + size - 1);
In the new form, we check all the cache lines and the final state of the machine. Since the final state starts with @@@ and covers a range of lines, I think it best to keep single lines of graded output beginning with one code and ranges of lines beginning with another code.
Also, my eventual goal is to add p1s as a submodule to p4 so that we have one central solution. The differences here make sure that p4 stuff isn't graded by p1s and p1s extra stuff isn't graded by p4

2021-11-10 13:52 UTC, nelsontm commented on projects/p4_spec.md
> +}
Fair enough

2021-11-10 13:54 UTC, nelsontm commented on projects/p4_spec.md
> +- Your cache simulator, a C program named `cache.c`
I think that since the simulator part is removed anyways, we might not need to keep checking against past semesters. I think MOSS would have trouble finding cheating since the p1s part is removed. Still, I would recommend changing past submissions to cache.c.

2021-11-10 13:55 UTC, nelsontm commented on projects/p4_spec.md
> +Linux workstation using `gcc cache.c inst_p1s_sim.o -lm`, so your program should
I'd say it's necessary just because cache.c is supposed to link with simulator.c. I don't think 2 files of the same name link together nicely.

2021-11-10 20:15 UTC, merged